server:  servlet:    context-path: /spring-security-oauth-server  port: 8081
spring:  h2:    console:      path: /h2      enabled: true      settings:        web-allow-others: true 
#spring.profiles.active=dev

#logging.level.org.springframework=DEBUG